// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('IMC', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('abaixo_fem', async function() {
    await driver.get("http://127.0.0.1:5500/")
    await driver.manage().window().setRect({ width: 1346, height: 708 })
    await driver.findElement(By.css(".name")).click()
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("41")
    await driver.findElement(By.css("form > div:nth-child(2)")).click()
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("155")
    await driver.findElement(By.id("sexo")).click()
    {
      const dropdown = await driver.findElement(By.id("sexo"))
      await dropdown.findElement(By.xpath("//option[. = 'Feminino']")).click()
    }
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.css("form > div:nth-child(2)")).getText() == "Altura em centímetros")
    await driver.close()
  })
  it('abaixo_masc', async function() {
    await driver.get("http://127.0.0.1:5500/indexIMC.html")
    await driver.manage().window().setRect({ width: 1346, height: 708 })
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("40")
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("150")
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.css("body")).getText() == "Peso em kilos\\\\nAltura em centímetros\\\\nSexo: \\\\n                \\\\nMasculino\\\\n                Feminino\\\\n             Calcular imc\\\\nSeu IMC é 17.8 e vc está com abaixo do peso ideal")
  })
  it('ideal_fem', async function() {
    await driver.get("http://127.0.0.1:5500/")
    await driver.manage().window().setRect({ width: 1346, height: 708 })
    await driver.findElement(By.css(".name")).click()
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("50")
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("150")
    await driver.findElement(By.id("sexo")).click()
    {
      const dropdown = await driver.findElement(By.id("sexo"))
      await dropdown.findElement(By.xpath("//option[. = 'Feminino']")).click()
    }
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.css("form > div:nth-child(2)")).getText() == "Altura em centímetros")
    await driver.close()
  })
  it('ideal_masc', async function() {
    await driver.get("http://127.0.0.1:5500/")
    await driver.manage().window().setRect({ width: 1346, height: 708 })
    await driver.findElement(By.css(".icon-html > .name")).click()
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("64")
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("170")
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.css("body")).getText() == "Peso em kilos\\\\nAltura em centímetros\\\\nSexo: \\\\n                \\\\nMasculino\\\\n                Feminino\\\\n             Calcular imc\\\\nSeu IMC é 22.1 e vc está com o peso ideal")
  })
  it('nulo_fem', async function() {
    await driver.get("http://127.0.0.1:5500/")
    await driver.manage().window().setRect({ width: 1346, height: 708 })
    await driver.findElement(By.css(".name")).click()
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("0")
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("0")
    await driver.findElement(By.id("sexo")).click()
    {
      const dropdown = await driver.findElement(By.id("sexo"))
      await dropdown.findElement(By.xpath("//option[. = 'Feminino']")).click()
    }
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.css("form")).getText() == "Peso em kilos\\\\nAltura em centímetros\\\\nSexo: \\\\n                \\\\nMasculino\\\\n                Feminino\\\\n             Calcular imc")
    await driver.close()
  })
  it('obeso_fem', async function() {
    await driver.get("http://127.0.0.1:5500/")
    await driver.manage().window().setRect({ width: 1346, height: 708 })
    await driver.findElement(By.css(".name")).click()
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("90")
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("170")
    await driver.findElement(By.id("sexo")).click()
    {
      const dropdown = await driver.findElement(By.id("sexo"))
      await dropdown.findElement(By.xpath("//option[. = 'Feminino']")).click()
    }
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.css("form")).getText() == "Peso em kilos\\\\nAltura em centímetros\\\\nSexo: \\\\n                \\\\nMasculino\\\\n                Feminino\\\\n             Calcular imc")
    await driver.close()
  })
  it('obeso_masc', async function() {
    await driver.get("http://127.0.0.1:5500/")
    await driver.manage().window().setRect({ width: 1346, height: 708 })
    await driver.findElement(By.css(".icon-html > .name")).click()
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("85")
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("160")
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.id("result")).getText() == "Seu IMC é 33.2 e vc está obeso")
    await driver.close()
  })
  it('sobrepeso_fem', async function() {
    await driver.get("http://127.0.0.1:5500/")
    await driver.manage().window().setRect({ width: 1346, height: 708 })
    await driver.findElement(By.css(".name")).click()
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("60")
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("150")
    await driver.findElement(By.id("sexo")).click()
    {
      const dropdown = await driver.findElement(By.id("sexo"))
      await dropdown.findElement(By.xpath("//option[. = 'Feminino']")).click()
    }
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.css("div:nth-child(1) > p")).getText() == "Peso em kilos")
    await driver.close()
  })
  it('sobrepeso_masc', async function() {
    await driver.get("http://127.0.0.1:5500/")
    await driver.manage().window().setRect({ width: 1346, height: 708 })
    await driver.findElement(By.css(".icon-html > .name")).click()
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("65")
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("150")
    await driver.findElement(By.css("button")).click()
    {
      const element = await driver.findElement(By.css("button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    assert(await driver.findElement(By.css("body > div")).getText() == "Peso em kilos\\\\nAltura em centímetros\\\\nSexo: \\\\n                \\\\nMasculino\\\\n                Feminino\\\\n             Calcular imc\\\\nSeu IMC é 28.9 e vc está com sobrepeso")
    await driver.close()
  })
  it('nulo_masc', async function() {
    await driver.get("http://127.0.0.1:5500/")
    await driver.manage().window().setRect({ width: 1346, height: 708 })
    await driver.findElement(By.css(".name")).click()
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("0")
    await driver.findElement(By.css("form > div:nth-child(2)")).click()
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("0")
    await driver.findElement(By.css("button")).click()
    assert(await driver.findElement(By.css("div:nth-child(2) > p")).getText() == "Altura em centímetros")
    await driver.close()
  })
})
