// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class IMCTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void abaixofem() {
    driver.get("http://127.0.0.1:5500/");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.cssSelector(".name")).click();
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("41");
    driver.findElement(By.cssSelector("form > div:nth-child(2)")).click();
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("155");
    driver.findElement(By.id("sexo")).click();
    {
      WebElement dropdown = driver.findElement(By.id("sexo"));
      dropdown.findElement(By.xpath("//option[. = 'Feminino']")).click();
    }
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("form > div:nth-child(2)")).getText(), is("Altura em centímetros"));
    driver.close();
  }
  @Test
  public void abaixomasc() {
    driver.get("http://127.0.0.1:5500/indexIMC.html");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("40");
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("150");
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("body")).getText(), is("Peso em kilos\\\\nAltura em centímetros\\\\nSexo: \\\\n                \\\\nMasculino\\\\n                Feminino\\\\n             Calcular imc\\\\nSeu IMC é 17.8 e vc está com abaixo do peso ideal"));
  }
  @Test
  public void idealfem() {
    driver.get("http://127.0.0.1:5500/");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.cssSelector(".name")).click();
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("50");
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("150");
    driver.findElement(By.id("sexo")).click();
    {
      WebElement dropdown = driver.findElement(By.id("sexo"));
      dropdown.findElement(By.xpath("//option[. = 'Feminino']")).click();
    }
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("form > div:nth-child(2)")).getText(), is("Altura em centímetros"));
    driver.close();
  }
  @Test
  public void idealmasc() {
    driver.get("http://127.0.0.1:5500/");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.cssSelector(".icon-html > .name")).click();
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("64");
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("170");
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("body")).getText(), is("Peso em kilos\\\\nAltura em centímetros\\\\nSexo: \\\\n                \\\\nMasculino\\\\n                Feminino\\\\n             Calcular imc\\\\nSeu IMC é 22.1 e vc está com o peso ideal"));
  }
  @Test
  public void nulofem() {
    driver.get("http://127.0.0.1:5500/");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.cssSelector(".name")).click();
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("0");
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("0");
    driver.findElement(By.id("sexo")).click();
    {
      WebElement dropdown = driver.findElement(By.id("sexo"));
      dropdown.findElement(By.xpath("//option[. = 'Feminino']")).click();
    }
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("form")).getText(), is("Peso em kilos\\\\nAltura em centímetros\\\\nSexo: \\\\n                \\\\nMasculino\\\\n                Feminino\\\\n             Calcular imc"));
    driver.close();
  }
  @Test
  public void obesofem() {
    driver.get("http://127.0.0.1:5500/");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.cssSelector(".name")).click();
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("90");
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("170");
    driver.findElement(By.id("sexo")).click();
    {
      WebElement dropdown = driver.findElement(By.id("sexo"));
      dropdown.findElement(By.xpath("//option[. = 'Feminino']")).click();
    }
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("form")).getText(), is("Peso em kilos\\\\nAltura em centímetros\\\\nSexo: \\\\n                \\\\nMasculino\\\\n                Feminino\\\\n             Calcular imc"));
    driver.close();
  }
  @Test
  public void obesomasc() {
    driver.get("http://127.0.0.1:5500/");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.cssSelector(".icon-html > .name")).click();
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("85");
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("160");
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("Seu IMC é 33.2 e vc está obeso"));
    driver.close();
  }
  @Test
  public void sobrepesofem() {
    driver.get("http://127.0.0.1:5500/");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.cssSelector(".name")).click();
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("60");
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("150");
    driver.findElement(By.id("sexo")).click();
    {
      WebElement dropdown = driver.findElement(By.id("sexo"));
      dropdown.findElement(By.xpath("//option[. = 'Feminino']")).click();
    }
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("div:nth-child(1) > p")).getText(), is("Peso em kilos"));
    driver.close();
  }
  @Test
  public void sobrepesomasc() {
    driver.get("http://127.0.0.1:5500/");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.cssSelector(".icon-html > .name")).click();
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("65");
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("150");
    driver.findElement(By.cssSelector("button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.findElement(By.cssSelector("body > div")).getText(), is("Peso em kilos\\\\nAltura em centímetros\\\\nSexo: \\\\n                \\\\nMasculino\\\\n                Feminino\\\\n             Calcular imc\\\\nSeu IMC é 28.9 e vc está com sobrepeso"));
    driver.close();
  }
  @Test
  public void nulomasc() {
    driver.get("http://127.0.0.1:5500/");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.cssSelector(".name")).click();
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("0");
    driver.findElement(By.cssSelector("form > div:nth-child(2)")).click();
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("0");
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("div:nth-child(2) > p")).getText(), is("Altura em centímetros"));
    driver.close();
  }
}
